steps:
  - name: 'gcr.io/cloud-builders/mvn'
    id: DEPLOY
    args: ['-Ddocker.image.prefix=gcr.io/ceres-dev-222017', 'package', 'jib:dockerBuild']

images:
  - 'gcr.io/ceres-dev-222017/metrics-query-service'
  - 'gcr.io/ceres-dev-222017/metrics-query-service:$REVISION_ID'
  - 'gcr.io/ceres-dev-222017/metrics-query-service:$BRANCH_NAME'
  - 'gcr.io/ceres-dev-222017/metrics-query-service:$SHORT_SHA'
