server:
  port: 8080

---
spring:
  profiles: development

database:
  url: "http://localhost:8086"

logging:
  level:
    com.rackspacecloud: debug

---
spring:
  profiles: production

database:
  url: ${INFLUXDB_URL}

logging:
  level:
    com.rackspacecloud: info